apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "compra-back.fullname" . }}-config
  labels:
    {{- include "compra-back.labels" . | nindent 4 }}
data:
  PORT: "8080"
  ENV: {{ .Values.config.env | quote }}
  DB_HOST: {{ .Values.config.dbHost | quote }}
  DB_PORT: {{ .Values.config.dbPort | quote }}
  DB_NAME: {{ .Values.config.dbName | quote }}
  DB_SSL_MODE: {{ .Values.config.dbSslMode | quote }}
  CORS_ALLOWED_ORIGINS: {{ .Values.config.corsAllowedOrigins | quote }}
  SCRAPER_CRON: {{ .Values.config.scraperCron | quote }}
  MERCADONA_POSTAL_CODE: {{ .Values.config.mercadonaPostalCode | quote }}
