apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "compra-back.fullname" . }}
  labels:
    {{- include "compra-back.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "compra-back.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "compra-back.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.image.pullSecretName }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecretName }}
      {{- end }}
      containers:
        - name: compra-back
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: {{ include "compra-back.fullname" . }}-config
            - secretRef:
                name: {{ .Values.secretName }}
          livenessProbe:
            httpGet:
              path: /livez
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
